const char* connect_page_html = "<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"UTF-8\" />\n"
"    <link rel=\"stylesheet\" href=\"./style.css\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"    <title>Pen</title>\n"
"  </head>\n"
"  <body>\n"
"    <h1>Подключение к сети WiFi</h1>\n"
"    <form method=\"get\" action=\"/submit\">\n"
"      <input type=\"text\" name=\"ssid\" placeholder=\"Имя сети\" />\n"
"      <input type=\"password\" name=\"pass\" placeholder=\"Пароль\" />\n"
"      <input type=\"submit\" value=\"Подключиться\" />\n"
"    </form>\n"
"    <script src=\"./script.js\"></script>\n"
"    <style>\n"
"      * {\n"
"        box-sizing: border-box;\n"
"      }\n"
"      html {\n"
"        height: 100%;\n"
"        width: 100%;\n"
"      }\n"
"      h1 {\n"
"        font-size: 3rem;\n"
"        text-align: center;\n"
"      }\n"
"      body {\n"
"        width: 100%;\n"
"        height: 100%;\n"
"        background-color: #191a1b;\n"
"        display: flex;\n"
"        flex-direction: column;\n"
"        justify-content: center;\n"
"        align-items: center;\n"
"        margin: 0;\n"
"        color: white;\n"
"        font-family: monospace;\n"
"        padding: 0.5rem;\n"
"      }\n"
"      form {\n"
"        display: flex;\n"
"        flex-direction: column;\n"
"        align-items: center;\n"
"      }\n"
"      input {\n"
"        width: 100%;\n"
"        display: block;\n"
"        margin: 0.5rem;\n"
"        padding: 0.4rem 1rem;\n"
"        font-size: 2rem;\n"
"        background-color: #36383b;\n"
"        border-radius: 9999px;\n"
"        border: 0px;\n"
"        color: white;\n"
"      }\n"
"      input:focus {\n"
"        outline: none;\n"
"      }\n"
"      input[type=\"submit\"] {\n"
"        background-color: #006edb;\n"
"        cursor: pointer;\n"
"      }\n"
"      input[type=\"submit\"]:active {\n"
"        background-color: #00458a;\n"
"      }\n"
"      @media (max-width: 370px) {\n"
"        input {\n"
"          font-size: 1rem;\n"
"        }\n"
"        h1 {\n"
"          font-size: 2rem;\n"
"        }\n"
"      }\n"
"    </style>\n"
"  </body>\n"
"</html>\n"
"";
